<?php

namespace App\Console\Commands;

use App\Models\Products;
use Illuminate\Console\Command;

class CreateProducts extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'create:products';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $products = [
            [
                'product_name' => 'Coffee Product 1',
                'descriptions' => 'Description for Coffee Product 1',
                'product_images' => 'coffee1.jpg',
                'product_category' =>'Coffee',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Coffee Product 2',
                'descriptions' => 'Description for Coffee Product 2',
                'product_images' => 'coffee2.jpg',
                'product_category' =>'Coffee',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Coffee Product 3',
                'descriptions' => 'Description for Coffee Product 3',
                'product_images' => 'coffee3.jpg',
                'product_category' =>'Coffee',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Coffee Product 4',
                'descriptions' => 'Description for Coffee Product 4',
                'product_images' => 'coffee4.jpg',
                'product_category' =>'Coffee',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Coffee Product 5',
                'descriptions' => 'Description for Coffee Product 5',
                'product_images' => 'coffee5.jpg',
                'product_category' =>'Coffee',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Coffee Product 6',
                'descriptions' => 'Description for Coffee Product 6',
                'product_images' => 'coffee6.jpg',
                'product_category' =>'Coffee',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Coffee Product 7',
                'descriptions' => 'Description for Coffee Product 7',
                'product_images' => 'coffee7.jpg',
                'product_category' =>'Coffee',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Coffee Product 8',
                'descriptions' => 'Description for Coffee Product 8',
                'product_images' => 'coffee8.jpg',
                'product_category' =>'Coffee',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Coffee Product 9',
                'descriptions' => 'Description for Coffee Product 9',
                'product_images' => 'coffee9.jpg',
                'product_category' =>'Coffee',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Coffee Product 10',
                'descriptions' => 'Description for Coffee Product 10',
                'product_images' => 'coffee10.jpg',
                'product_category' =>'Coffee',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Cloud Product 1',
                'descriptions' => 'Description for Cloud Product 1',
                'product_images' => 'Cloud1.jpg',
                'product_category' =>'Cloud',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Cloud Product 2',
                'descriptions' => 'Description for Cloud Product 2',
                'product_images' => 'Cloud2.jpg',
                'product_category' =>'Cloud',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Cloud Product 3',
                'descriptions' => 'Description for Cloud Product 3',
                'product_images' => 'Cloud3.jpg',
                'product_category' =>'Cloud',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Cloud Product 4',
                'descriptions' => 'Description for Cloud Product 4',
                'product_images' => 'Cloud4.jpg',
                'product_category' =>'Cloud',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Cloud Product 5',
                'descriptions' => 'Description for Cloud Product 5',
                'product_images' => 'Cloud5.jpg',
                'product_category' =>'Cloud',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Cloud Product 6',
                'descriptions' => 'Description for Cloud Product 6',
                'product_images' => 'Cloud6.jpg',
                'product_category' =>'Cloud',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Cloud Product 7',
                'descriptions' => 'Description for Cloud Product 7',
                'product_images' => 'Cloud7.jpg',
                'product_category' =>'Cloud',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Cloud Product 8',
                'descriptions' => 'Description for Cloud Product 8',
                'product_images' => 'Cloud8.jpg',
                'product_category' =>'Cloud',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Cloud Product 9',
                'descriptions' => 'Description for Cloud Product 9',
                'product_images' => 'Cloud9.jpg',
                'product_category' =>'Cloud',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Cloud Product 10',
                'descriptions' => 'Description for Cloud Product 10',
                'product_images' => 'Cloud10.jpg',
                'product_category' =>'Cloud',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Tea Product 1',
                'descriptions' => 'Description for Tea Product 1',
                'product_images' => 'tea1.jpg',
                'product_category' =>'tea',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Tea Product 2',
                'descriptions' => 'Description for Tea Product 2',
                'product_images' => 'tea2.jpg',
                'product_category' =>'tea',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Tea Product 3',
                'descriptions' => 'Description for Tea Product 3',
                'product_images' => 'tea3.jpg',
                'product_category' =>'tea',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Tea Product 4',
                'descriptions' => 'Description for Tea Product 4',
                'product_images' => 'tea4.jpg',
                'product_category' =>'tea',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Tea Product 5',
                'descriptions' => 'Description for Tea Product 5',
                'product_images' => 'tea5.jpg',
                'product_category' =>'tea',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Tea Product 6',
                'descriptions' => 'Description for Tea Product 6',
                'product_images' => 'tea6.jpg',
                'product_category' =>'tea',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Tea Product 7',
                'descriptions' => 'Description for Tea Product 7',
                'product_images' => 'tea7.jpg',
                'product_category' =>'tea',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Tea Product 8',
                'descriptions' => 'Description for Tea Product 8',
                'product_images' => 'tea8.jpg',
                'product_category' =>'tea',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Tea Product 9',
                'descriptions' => 'Description for Tea Product 9',
                'product_images' => 'tea9.jpg',
                'product_category' =>'tea',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Tea Product 10',
                'descriptions' => 'Description for Tea Product 10',
                'product_images' => 'tea10.jpg',
                'product_category' =>'tea',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Green tea Product 1',
                'descriptions' => 'Description for Green tea Product 1',
                'product_images' => 'Green tea1.jpg',
                'product_category' =>'Green tea',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Green tea Product 2',
                'descriptions' => 'Description for Green tea Product 2',
                'product_images' => 'Green tea2.jpg',
                'product_category' =>'Green tea',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Green tea Product 3',
                'descriptions' => 'Description for Green tea Product 3',
                'product_images' => 'Green tea3.jpg',
                'product_category' =>'Green tea',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Green tea Product 4',
                'descriptions' => 'Description for Green tea Product 4',
                'product_images' => 'Green tea4.jpg',
                'product_category' =>'Green tea',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Green tea Product 5',
                'descriptions' => 'Description for Green tea Product 5',
                'product_images' => 'Green tea5.jpg',
                'product_category' =>'Green tea',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Green tea Product 6',
                'descriptions' => 'Description for Green tea Product 6',
                'product_images' => 'Green tea6.jpg',
                'product_category' =>'Green tea',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Green tea Product 7',
                'descriptions' => 'Description for Green tea Product 7',
                'product_images' => 'Green tea7.jpg',
                'product_category' =>'Green tea',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Green tea Product 8',
                'descriptions' => 'Description for Green tea Product 8',
                'product_images' => 'Green tea8.jpg',
                'product_category' =>'Green tea',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Green tea Product 9',
                'descriptions' => 'Description for Green tea Product 9',
                'product_images' => 'Green tea9.jpg',
                'product_category' =>'Green tea',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Green tea Product 10',
                'descriptions' => 'Description for Green tea Product 10',
                'product_images' => 'Green tea10.jpg',
                'product_category' =>'Green tea',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Frosty Product 1',
                'descriptions' => 'Description for Frosty Product 1',
                'product_images' => 'Frosty1.jpg',
                'product_category' =>'Frosty',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Frosty Product 2',
                'descriptions' => 'Description for Frosty Product 2',
                'product_images' => 'Frosty2.jpg',
                'product_category' =>'Frosty',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Frosty Product 3',
                'descriptions' => 'Description for Frosty Product 3',
                'product_images' => 'Frosty3.jpg',
                'product_category' =>'Frosty',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Frosty Product 4',
                'descriptions' => 'Description for Frosty Product 4',
                'product_images' => 'Frosty4.jpg',
                'product_category' =>'Frosty',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Frosty Product 5',
                'descriptions' => 'Description for Frosty Product 5',
                'product_images' => 'Frosty5.jpg',
                'product_category' =>'Frosty',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Frosty Product 6',
                'descriptions' => 'Description for Frosty Product 6',
                'product_images' => 'Frosty6.jpg',
                'product_category' =>'Frosty',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Frosty Product 7',
                'descriptions' => 'Description for Frosty Product 7',
                'product_images' => 'Frosty7.jpg',
                'product_category' =>'Frosty',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Frosty Product 8',
                'descriptions' => 'Description for Frosty Product 8',
                'product_images' => 'Frosty8.jpg',
                'product_category' =>'Frosty',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Frosty Product 9',
                'descriptions' => 'Description for Frosty Product 9',
                'product_images' => 'Frosty9.jpg',
                'product_category' =>'Frosty',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Frosty Product 10',
                'descriptions' => 'Description for Frosty Product 10',
                'product_images' => 'Frosty10.jpg',
                'product_category' =>'Frosty',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Chocolate Product 10',
                'descriptions' => 'Description for Chocolate Product 1',
                'product_images' => 'Chocolate.jpg',
                'product_category' =>'Chocolate',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Frosty Product 1',
                'descriptions' => 'Description for Frosty Product 1',
                'product_images' => 'Frosty1.jpg',
                'product_category' =>'Frosty',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Frosty Product 2',
                'descriptions' => 'Description for Frosty Product 2',
                'product_images' => 'Frosty2.jpg',
                'product_category' =>'Frosty',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Frosty Product 3',
                'descriptions' => 'Description for Frosty Product 3',
                'product_images' => 'Frosty3.jpg',
                'product_category' =>'Frosty',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Frosty Product 4',
                'descriptions' => 'Description for Frosty Product 4',
                'product_images' => 'Frosty4.jpg',
                'product_category' =>'Frosty',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Frosty Product 5',
                'descriptions' => 'Description for Frosty Product 5',
                'product_images' => 'Frosty5.jpg',
                'product_category' =>'Frosty',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Frosty Product 6',
                'descriptions' => 'Description for Frosty Product 6',
                'product_images' => 'Frosty6.jpg',
                'product_category' =>'Frosty',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Frosty Product 7',
                'descriptions' => 'Description for Frosty Product 7',
                'product_images' => 'Frosty7.jpg',
                'product_category' =>'Frosty',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Frosty Product 8',
                'descriptions' => 'Description for Frosty Product 8',
                'product_images' => 'Frosty8.jpg',
                'product_category' =>'Frosty',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Frosty Product 9',
                'descriptions' => 'Description for Frosty Product 9',
                'product_images' => 'Frosty9.jpg',
                'product_category' =>'Frosty',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Frosty Product 10',
                'descriptions' => 'Description for Frosty Product 10',
                'product_images' => 'Frosty10.jpg',
                'product_category' =>'Frosty',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Savory cake Product 1',
                'descriptions' => 'Description for Savory cake Product 1',
                'product_images' => 'Savory1.jpg',
                'product_category' =>'Savory cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Savory cake Product 2',
                'descriptions' => 'Description for Savory cake Product 2',
                'product_images' => 'Savory2.jpg',
                'product_category' =>'Savory cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Savory cake Product 3',
                'descriptions' => 'Description for Savory cake Product 3',
                'product_images' => 'Savory3.jpg',
                'product_category' =>'Savory cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Savory cake Product 4',
                'descriptions' => 'Description for Savory cake Product 4',
                'product_images' => 'Savory4.jpg',
                'product_category' =>'Savory cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Savory cake Product 5',
                'descriptions' => 'Description for Savory cake Product 5',
                'product_images' => 'Savory5.jpg',
                'product_category' =>'Savory cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Savory cake Product 6',
                'descriptions' => 'Description for Savory cake Product 6',
                'product_images' => 'Savory6.jpg',
                'product_category' =>'Savory cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Savory cake Product 7',
                'descriptions' => 'Description for Savory cake Product 7',
                'product_images' => 'Savory7.jpg',
                'product_category' =>'Savory cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Savory cake Product 8',
                'descriptions' => 'Description for Savory cake Product 8',
                'product_images' => 'Savory8.jpg',
                'product_category' =>'Savory cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Savory cake Product 9',
                'descriptions' => 'Description for Savory cake Product 9',
                'product_images' => 'Savory9.jpg',
                'product_category' =>'Savory cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Savory cake Product 10',
                'descriptions' => 'Description for Savory cake Product 10',
                'product_images' => 'Savory10.jpg',
                'product_category' =>'Savory cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Sweet cake Product 1',
                'descriptions' => 'Description for Sweet cake Product 1',
                'product_images' => 'Sweet1.jpg',
                'product_category' =>'Sweet cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Sweet cake Product 2',
                'descriptions' => 'Description for Sweet cake Product 2',
                'product_images' => 'Sweet2.jpg',
                'product_category' =>'Sweet cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Sweet cake Product 3',
                'descriptions' => 'Description for Sweet cake Product 3',
                'product_images' => 'Sweet3.jpg',
                'product_category' =>'Sweet cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Sweet cake Product 4',
                'descriptions' => 'Description for Sweet cake Product 4',
                'product_images' => 'Sweet4.jpg',
                'product_category' =>'Sweet cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Sweet cake Product 5',
                'descriptions' => 'Description for Sweet cake Product 5',
                'product_images' => 'Sweet5.jpg',
                'product_category' =>'Sweet cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Sweet cake Product 6',
                'descriptions' => 'Description for Sweet cake Product 6',
                'product_images' => 'Sweet6.jpg',
                'product_category' =>'Sweet cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Sweet cake Product 7',
                'descriptions' => 'Description for Sweet cake Product 7',
                'product_images' => 'Sweet7.jpg',
                'product_category' =>'Sweet cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Sweet cake Product 8',
                'descriptions' => 'Description for Sweet cake Product 8',
                'product_images' => 'Sweet8.jpg',
                'product_category' =>'Sweet cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Sweet cake Product 9',
                'descriptions' => 'Description for Sweet cake Product 9',
                'product_images' => 'Sweet9.jpg',
                'product_category' =>'Sweet cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Sweet cake Product 10',
                'descriptions' => 'Description for Sweet cake Product 10',
                'product_images' => 'Sweet10.jpg',
                'product_category' =>'Sweet cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Snack Product 1',
                'descriptions' => 'Description for Snack Product 9',
                'product_images' => 'Sweet9.jpg',
                'product_category' =>'Snack',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Snack Product 2',
                'descriptions' => 'Description for Snack Product 10',
                'product_images' => 'Sweet10.jpg',
                'product_category' =>'Snack',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Pastry cake Product 1',
                'descriptions' => 'Description for Pastry cake Product 1',
                'product_images' => 'Pastry1.jpg',
                'product_category' =>'Pastry cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Pastry cake Product 2',
                'descriptions' => 'Description for Pastry cake Product 2',
                'product_images' => 'Pastry2.jpg',
                'product_category' =>'Pastry cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],
            [
                'product_name' => 'Pastry cake Product 3',
                'descriptions' => 'Description for Pastry cake Product 3',
                'product_images' => 'Pastry3.jpg',
                'product_category' =>'Pastry cake',
                'status' => 1,
                'status_in_stock' => 1,
            ],

        ];

        // Seed products
        foreach ($products as $productData) {
            Products::create($productData);
            $this->info('Product ' . $productData['product_name'] . ' seeded successfully.');
        }

        $this->info('Products seeding completed.');
    }
}
